
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cust?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
  thymeleaf:
    cache: false



mybatis:
  type-aliases-package: com.lijintong.model
  mapper-locations: classpath:mybatis/mapper/*.xml


